### ISSUE TITLE
Seg Fault

### ISSUE THREAD

**Issue by yiyinglai** [datasith/Ai_Demos_RPi#2]
Hi, I followed the steps but when I run `realsense-viewr`, I got ``Segmentation fault``. Do you know why that is?

I'm using Raspberry Pi 4B, OS: Raspbian Buster.

**Comment by datasith** [comment]
Can't seem to replicate this, procedure still works. Please double-check the installation process.

**Comment by eliotts** [comment]
Hi @themakerbro,
I also tried your installation procedure and also get the `Segmentation fault` @yiyinglai is describing above.
As soon as I run `realsense-viewer`, a window opens and closes before returning the `Segmentation fault` error
I have a Raspberry Pi 4B, 8GB ram, also running with Raspbian Buster with ROS Kinetic installed.
Linux rpsPi 5.10.17-v7l+ armv7l GNU/Linux

Have you heard of similar issues? 
Thanks
