### ISSUE TITLE
GLFW Driver Error: GLX: GLX version 1.3 is required Could not initialize offscreen context!

### ISSUE THREAD

**Issue by bestaps** [datasith/Ai_Demos_RPi#3]
hi! followed your tutorial but I am encountering this error and I tried to rebuild according to instructions but no luck. any solution ?

**Comment by johnhanckel** [comment]
Hi bestaps! Quick clarification question, are you attempting to do this method headless as the instructions say?

**Comment by bestaps** [comment]
Hi @johnhanckel , yes, I attempted to do this in headless as instruction says. and I resolved it by connecting it to a monitor via HDMI port. I believe its something to do with the virtual OpenGL driver on raspi. any further explanations you have? 

IntelRealSense/librealsense#7343

**Comment by johnhanckel** [comment]
I resolved it the same way, so I don't really have any better explanation. Personally, I think it has something to do with the resolution adjustments from the raspi window to the laptop, and the fact that they will most likely be incompatible. I have nothing to tell me whether or not that's true, it's just my theory. Glad you were at least able to hook it up to the monitor though!

**Comment by bestaps** [comment]
> I resolved it the same way, so I don't really have any better explanation. Personally, I think it has something to do with the resolution adjustments from the raspi window to the laptop, and the fact that they will most likely be incompatible. I have nothing to tell me whether or not that's true, it's just my theory. Glad you were at least able to hook it up to the monitor though!


@johnhanckel I did some research in meanwhile and found these references on raspberrypi Github issues. raspberrypi/Raspberry-Pi-OS-64bit#21 and raspberrypi/Raspberry-Pi-OS-64bit#3  
what I understood is that the source of error is using virtual vncserver that isn't enabled via `sudo raspi-config` . I usually run vncserver via `vncserver` command in putty terminal. which results in 
pi@raspberrypi:~ $ glxgears -info
GL_RENDERER = llvmpipe (LLVM 9.0.1, 128 bits)
GL_VERSION = 3.1 Mesa 19.3.2
GL_VENDOR = **VMware, Inc**.
a VMware based driver which comes with virtual vnc display.

if I activate vncserver via `sudo raspi-config` -> `interfacing options` -> `vncserver` -> `enable` and directly login from realvnc app then I get 
pi@raspberrypi:~ $ glxgears -info
GL_RENDERER = V3D 4.2
GL_VERSION = 2.1 Mesa 19.3.2
GL_VENDOR = **Broadcom**

in which case the `realsense-viewer` command works from realvnc-viewer windows 10 app itself.
